### ISSUE TITLE
No USB device found message persists

### ISSUE THREAD

**Issue by atmahesh8** [nos/client#148]
An error message after finding nano ledger - No USB device found.

## Expected Behavior

Only `Found USB Ledger Nano S` should be displayed. 

## Current Behavior

`No USB device found` is also being displayed in addition to `Found USB Ledger Nano S`
<img width="424" alt="screen shot 2018-05-14 at 9 38 50 pm" src="https://user-images.githubusercontent.com/39273533/40011406-61310d4a-57c5-11e8-8f7d-e43ff4d34163.png">

## Possible Solution

Removing `No USB device found` message when detected ledger. 

## Steps to Reproduce (for bugs)

1. Go to Ledger tab in nOS
2. Open NEO in Ledger
3. Ledger tab will display
```Connected to ledger
Found USB Ledger Nano S
No USB device found
```

## Context

No negative side-effects, UI issue

## Your Environment

* Version used:
* Environment name and version (e.g. node.js 9.6.1, yarn 1.6.1, npm 5.6.0): Yarn 1.5.1 / 1.6.0, Node v8.9.1 / v10.1.0
* Operating System and version (desktop or mobile): macOS Sierra
* Ledger Nano S firmware : 1.4.2

**Comment by jeroenptrs** [comment]
@atmahesh8 thank you for all the Ledger related issues you've been opening, it's nice to have someone with a Ledger helping us out with bugs/issues/functionality.

However, please refrain from editing the formatting of the Issue template 😛 makes the issues unreadable. I'll edit your issues and titles to make them a bit more readable.

**Comment by atmahesh8** [comment]
thanks @jeroenptrs . I took a note of formatting.

**Comment by atmahesh8** [comment]
While debugging this issue I found out that it is related to ledger version firmware version. ( update ledger version in the environment) . 

I am now getting three errors randomly when NEO app is open in the ledger. 

1.  `Invalid sequence`
2.  `Cannot open device with path. `( As reported in https://github.com/nos/client/issues/151) 

 <img width="1635" alt="screen shot 2018-05-18 at 12 03 08 am" src="https://user-images.githubusercontent.com/39273533/40196716-fd86e50a-5a2e-11e8-9c54-534df5054a0f.png">
3. `No USB device found`

<img width="1555" alt="screen shot 2018-05-17 at 11 56 27 pm" src="https://user-images.githubusercontent.com/39273533/40196729-04e2ff5a-5a2f-11e8-8fb8-9db97deb0aa0.png">

The same issue has been reported at CityOfZion/neon-wallet - Point 5, 7 and 8  at https://github.com/CityOfZion/neon-wallet/issues/798

It seems the issues are not fixed considering it as low priority bug. 

The potential fix I found is : 

https://github.com/LedgerHQ/ledgerjs/issues/146

> <img width="665" alt="image" src="https://user-images.githubusercontent.com/39273533/40196935-968dd66e-5a2f-11e8-94d3-add12cfd6991.png">

but not sure how to implement/fix .

**Comment by jeroenptrs** [comment]
This issue appears to have been fixed? @atmahesh8 can you confirm this?

**Comment by atmahesh8** [comment]
no. I just tested it on latest build but it is not fixed. will look into it.

**Comment by jeroenptrs** [comment]
@atmahesh8 is your ledger firmware up to date.

**Comment by atmahesh8** [comment]
Yes, Ledger Nano S firmware: 1.4.2, the update available in April. (mentioned in environment setup).

**Comment by tjuretzek** [comment]
I had trouble recreating it, but as soon as I succeeded I found some other issues relating the status texts (the detailed deviceInfo is only available after the NEO app on the ledger is opened and the publickey is provided, the login wasn't disabled after disconnect and the texts were inconsistent).
I created a PR and fixed the login behaviour for ledger devices to work as expected: https://github.com/nos/client/pull/186
